services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_POOL_IDLE: ${DB_POOL_IDLE}
      DB_POOL_MAX: ${DB_POOL_MAX}
      DB_POOL_MAX_LIFE_TIME: ${DB_POOL_MAX_LIFE_TIME}
      GRPC_HOST: ${GRPC_HOST}
      GRPC_PORT: ${GRPC_PORT}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      JWT_REFRESH_LIFE_TIME_DAY: ${JWT_REFRESH_LIFE_TIME_DAY}
      JWT_ACCESS_LIFE_TIME_MINUTE: ${JWT_ACCESS_LIFE_TIME_MINUTE}
      RABBITMQ_URL: ${RABBITMQ_URL}
      RABBITMQ_QUEUE_EVENT_NOTIFICATIONS: ${RABBITMQ_QUEUE_EVENT_NOTIFICATIONS}
      RABBITMQ_QUEUE_BROADCAST_NOTIFICATIONS: ${RABBITMQ_QUEUE_BROADCAST_NOTIFICATIONS}

    depends_on:
      - postgres
      - notification

  postgres:
    image: "postgres:13"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"

  notification:
    build: ~/GolandProjects/NotificationService/
    ports:
      - "5673:5673"
    environment:
      RABBITMQ_URL: ${RABBITMQ_URL}
      RABBITMQ_QUEUE_EVENT_NOTIFICATIONS: ${RABBITMQ_QUEUE_EVENT_NOTIFICATIONS}
      RABBITMQ_QUEUE_BROADCAST_NOTIFICATIONS: ${RABBITMQ_QUEUE_BROADCAST_NOTIFICATIONS}
    depends_on:
      - rabbitmq
  
  rabbitmq:
    image: "rabbitmq:3.10.7-management"
    environment:
      - RABBITMQ_DEFAULT_USER=sergeyiksanov
      - RABBITMQ_DEFAULT_PASS=&232717&Al
    ports:
      - "5672:5672"

  prometheus:
    image: "prom/prometheus:latest"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "19090:9090"

  grafana:
    image: "grafana/grafana-oss:9.4.3"
    ports:
      - "13000:3000"
